version: "3"

services: 
    app:
        build: 
            context: .
        volumes: 
            - static_data:/vol/web
        env_file: 
            - .env
        environment: 
            - SECRET_KEY=${SECRET_KEY}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}

    proxy:
        build: 
            context: ./proxy
        volumes: 
            - static_data:/vol/static
        ports: 
            - "9090:9090"
        depends_on: 
            - app

    db:
        image: mysql:latest
        ports:
            - '${SQL_PORT}:3306'
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '${PHPMYADMIN_PORT}:80'
        environment:
            PMA_HOST: db

volumes: 
    static_data: 