version: "3"

services: 
    app:
        build:
            context: .
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        restart: unless-stopped
        volumes: 
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:${SERVER_PORT}"
        env_file: 
            - .env
        depends_on: 
            - db

    db:
        image: mysql:latest
        ports:
            - '${SQL_PORT}:3306'
        restart: unless-stopped
        expose:
            - '3306'
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - my-db:/var/lib/mysql

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '${PHPMYADMIN_PORT}:80'
        environment:
            PMA_HOST: db

volumes:
  my-db: